name: chat_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  firebase_core: ^1.24.0
  firebase_storage: ^10.3.11
  firebase_auth: ^3.11.2
  image_picker: ^0.8.6
  google_sign_in: ^5.4.2
  introduction_screen: ^3.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  lottie: ^1.4.3
  get_it: ^7.2.0
  shared_preferences: ^2.0.15
  avatar_glow: ^2.0.2
  responsive_framework: ^0.2.0
  emoji_picker_flutter: ^1.5.0
  cloud_firestore: ^3.5.1
  json_annotation: ^4.7.0
  freezed_annotation: ^2.2.0

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/
