// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaowplT38lk2GCxPA3EzcTD5g0I0NMRgQ',
    appId: '1:468280535568:web:bf4898966fad4376577895',
    messagingSenderId: '468280535568',
    projectId: 'chat-app-e99bd',
    authDomain: 'chat-app-e99bd.firebaseapp.com',
    storageBucket: 'chat-app-e99bd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ0qDlZy0RgYMRk_L52ICrkO_5jfIXYD4',
    appId: '1:468280535568:android:fbd80f3a3d2ff876577895',
    messagingSenderId: '468280535568',
    projectId: 'chat-app-e99bd',
    storageBucket: 'chat-app-e99bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEYBGLN06bDEJrjfpwCPpeOO8iATGDPFk',
    appId: '1:468280535568:ios:12f1c9d4a5b5f0e4577895',
    messagingSenderId: '468280535568',
    projectId: 'chat-app-e99bd',
    storageBucket: 'chat-app-e99bd.appspot.com',
    iosClientId:
        '468280535568-sshn1057j4i4f441n7uts3lsrq3v12g2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEYBGLN06bDEJrjfpwCPpeOO8iATGDPFk',
    appId: '1:468280535568:ios:12f1c9d4a5b5f0e4577895',
    messagingSenderId: '468280535568',
    projectId: 'chat-app-e99bd',
    storageBucket: 'chat-app-e99bd.appspot.com',
    iosClientId:
        '468280535568-sshn1057j4i4f441n7uts3lsrq3v12g2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
